In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [10]:
def append_array_to_txt(filename, array, delimiter=',', fmt='%.2f'):
    
    with open(filename, 'a') as f:
        np.savetxt(f, array, fmt=fmt, delimiter=delimiter)

In [3]:
for n in range(0,18):
    for j in range(0,18):
        folder_path = f'Data_sets/智能（光电翰林哥数据）/{2*n+1}-{2*j+1}'
        file_list = sorted([f for f in os.listdir(folder_path) if f.endswith(".dat")])
        for i, filename in enumerate(file_list):
            # 构造完整的文件路径
            file_path = os.path.join(folder_path, filename)
            open_file = open(file_path, 'r')
            lines = open_file.readlines()
            data = np.zeros((2,2000))
            for i in range(2000):
                data[0,i] , data[1,i] = lines[i+2].split('\t')[1:3]
            append_array_to_txt('data.txt', data)


In [11]:
for i in range(324):
    data_y = np.zeros((12,2))
    for j in range(1,13):
        data_y[j-1,:] = [i+1,j]
    append_array_to_txt('data_y.txt', data_y)

In [6]:
data_y = np.zeros((12,2))
data_y[0,:] = [1,2]
data_y


array([[1., 2.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:

for i, filename in enumerate(file_list):
    # 构造完整的文件路径
    file_path = os.path.join(folder_path, filename)
    open_file = open(file_path, 'r')
    lines = open_file.readlines()
    data = np.zeros((2,2000))
    for i in range(2000):
        data[0,i] , data[1,i] = lines[i+2].split('\t')[1:3]
    


In [40]:
A = np.array([[3,1],
              [0,2]])
A.dot(np.array([[-1],
                [1]]))
B = np.array([[9, -10], 
              [0, 10]])
B_inv = np.linalg.inv(B)
print(f'{B_inv @ A @ B}')
print(B_inv)
print(B)

[[3.00000000e+00 1.11022302e-16]
 [0.00000000e+00 2.00000000e+00]]
[[0.11111111 0.11111111]
 [0.         0.1       ]]
[[  9 -10]
 [  0  10]]


array([[-1],
       [ 1]])

7.2.2


EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[ 1.        , -0.70710678],
       [ 0.        ,  0.70710678]]))